# Generated by Django 3.2.5 on 2021-11-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilephoto', models.ImageField(upload_to='portfolio/images/')),
                ('cvlink', models.URLField()),
                ('socialmedia_linkedin', models.URLField()),
                ('socialmedia_github', models.URLField()),
                ('socialmedia_stackoverflow', models.URLField()),
                ('socialmedia_insta', models.URLField()),
            ],
        ),
    ]
