# Generated by Django 3.2.5 on 2021-11-02 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_contact_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='address',
        ),
    ]
