# Generated by Django 3.2.5 on 2021-11-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20211106_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='url',
            new_name='projecturl',
        ),
        migrations.AddField(
            model_name='about',
            name='aboutmeimage',
            field=models.ImageField(blank=True, upload_to='portfolio/images/'),
        ),
    ]
