# Generated by Django 4.0.2 on 2022-03-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_remove_project_projecturl'),
    ]

    operations = [
        migrations.CreateModel(
            name='experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.CharField(blank=True, max_length=30)),
                ('ended', models.CharField(blank=True, max_length=30)),
                ('companyName', models.CharField(blank=True, max_length=50)),
                ('job_domain', models.CharField(blank=True, max_length=50)),
                ('description_of_job', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
