# Generated by Django 4.0.2 on 2022-03-02 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='ended',
            new_name='ended_month_year_or_present',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='started',
            new_name='started_month_year',
        ),
    ]
